package com.demo.rules;

import lombok.Data;
import lombok.experimental.Accessors;

import java.math.BigDecimal;

/**
 * This class was automatically generated by the data modeler tool.
 *
 * @author liuqiang
 * @date 2024/12/13
 */

@Data
@Accessors(chain = true)
public class SaleDtl implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    private Long clientManagerId;
    private String projectNo;
    @org.kie.api.definition.type.Label("产品名称")
    private String productName;
    @org.kie.api.definition.type.Label("基价值")
    private BigDecimal basicValue;

    @org.kie.api.definition.type.Label("提成金额")
    private BigDecimal royaltyAmount=new BigDecimal(0);

    @org.kie.api.definition.type.Label(value = "贷款金额")
    private BigDecimal loanAmount;

    @org.kie.api.definition.type.Label(value = "提成")
    private BigDecimal royaltyRate;

    @org.kie.api.definition.type.Label(value = "业务售价")
    private BigDecimal saleRate;
}
